import { NextResponse } from 'next/server';
import { detectPlatform, isValidUrl } from '@/lib/platform';
import type { DownloadType } from '@/types/media';

const downloadTypes = new Set<DownloadType>(['video', 'audio', 'thumbnail']);
const extensions: Record<DownloadType, string> = {
  video: 'mp4',
  audio: 'mp3',
  thumbnail: 'svg',
};
const contentTypes: Record<DownloadType, string> = {
  video: 'application/octet-stream',
  audio: 'application/octet-stream',
  thumbnail: 'image/svg+xml; charset=utf-8',
};

function sanitizeFilename(value: string) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '').slice(0, 48) || 'glassfetch-mock';
}

function escapeXml(value: string) {
  return value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&apos;');
}

function createMockFile({ type, url, title }: { type: DownloadType; url: string; title: string }) {
  if (type === 'thumbnail') {
    const safeTitle = escapeXml(title);
    const safeUrl = escapeXml(url);
    return `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="675" viewBox="0 0 1200 675">
  <defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#22d3ee"/><stop offset="0.55" stop-color="#8b5cf6"/><stop offset="1" stop-color="#f43f5e"/></linearGradient></defs>
  <rect width="1200" height="675" rx="44" fill="#070812"/>
  <circle cx="180" cy="120" r="180" fill="#22d3ee" opacity="0.28"/>
  <circle cx="1000" cy="560" r="240" fill="#8b5cf6" opacity="0.35"/>
  <rect x="80" y="80" width="1040" height="515" rx="36" fill="url(#g)" opacity="0.22" stroke="rgba(255,255,255,0.35)"/>
  <text x="110" y="315" fill="white" font-size="58" font-family="Arial, sans-serif" font-weight="800">GlassFetch Mock Thumbnail</text>
  <text x="110" y="380" fill="rgba(255,255,255,0.76)" font-size="30" font-family="Arial, sans-serif">${safeTitle}</text>
  <text x="110" y="438" fill="rgba(255,255,255,0.55)" font-size="22" font-family="Arial, sans-serif">${safeUrl}</text>
</svg>`;
  }

  return `GlassFetch mock ${type} file\n\nTitle: ${title}\nSource URL: ${url}\n\nThis is a legal placeholder file generated by /api/download. It does not contain scraped platform media, DRM bypass output, or protected content.\n`;
}

export async function POST(request: Request) {
  try {
    const body = (await request.json()) as { url?: unknown; type?: unknown; title?: unknown };
    const url = typeof body.url === 'string' ? body.url.trim() : '';
    const type = typeof body.type === 'string' && downloadTypes.has(body.type as DownloadType) ? (body.type as DownloadType) : null;
    const title = typeof body.title === 'string' && body.title.trim() ? body.title.trim() : 'GlassFetch mock media';

    if (!url || !isValidUrl(url)) {
      return NextResponse.json({ error: 'URL http/https yang valid diperlukan.' }, { status: 400 });
    }

    if (!type) {
      return NextResponse.json({ error: 'Format download tidak valid.' }, { status: 400 });
    }

    if (detectPlatform(url) === 'Unknown') {
      return NextResponse.json({ error: 'Platform belum didukung untuk mock download.' }, { status: 422 });
    }

    const filename = `${sanitizeFilename(title)}-${type}.${extensions[type]}`;
    const file = createMockFile({ type, url, title });

    return new NextResponse(file, {
      headers: {
        'Content-Type': contentTypes[type],
        'Content-Disposition': `attachment; filename="${filename}"`,
        'Cache-Control': 'no-store',
      },
    });
  } catch {
    return NextResponse.json({ error: 'Tidak dapat membuat mock file download.' }, { status: 500 });
  }
}
